image:
  file: .gitpod.Dockerfile

tasks:
  - name: Containers
    before: |
      docker run -p 5432:5432 --rm -e POSTGRES_DB=eventaservo_devel -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -v postgres_db:/var/lib/postgresql/data -d --name postgres postgres:13.5
      docker run -p 6379:6379 --rm -d --name redis redis:6.2.6
      docker run -p 1025:1025 --rm -p 1080:1080 -d schickling/mailcatcher:latest
      gp sync-done containers
      exit

  - name: Bundler
    init: |
      gp sync-await containers
      gem install solargraph
      gem install bundler:2.3.18
      bundle install
      bundle exec rails db:migrate
      bundle exec rails db:seed
    command: |
      gp sync-done bundler
      exit

  - name: Yarn
    init: |
      yarn install
    command: |
      gp sync-done yarn
      exit

  - name: Delayed Job
    command: |
      gp sync-await bundler
      gp sync-await yarn
      bundle exec bin/rake jobs:work

  - name: Webpacker
    command: |
      gp sync-await bundler
      gp sync-await yarn
      bundle exec bin/webpack-dev-server

  - name: Rails server
    command: |
      gp sync-await bundler
      gp sync-await yarn
      bundle exec bin/rails server -b 0.0.0.0 -p 3000 -e development -b 'ssl://0.0.0.0:3000?key=./certs/localhost.key&cert=./certs/localhost.crt'

  - name: Rails console
    command: |
      gp sync-await bundler
      gp sync-await yarn
      bundle exec bin/rails console

ports:
  - port: 3000
    visibility: public
  - port: 3035
    visibility: private
  - port: 6379
    visibility: private
  - port: 5432
    visibility: private

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - mhutchie.git-graph
    - PKief.material-icon-theme
    - rebornix.ruby
    - eamodio.gitlens
    - kaiwood.endwise
    - noku.rails-run-spec-vscode
    - makicamel.rails-routes-navigator
    - castwide.solargraph
    - karunamurti.haml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addCheck: true
    addBadge: true
