# Docker-compose file for DEVELOPMENT containers
version: '3.8'

services:
  rails:
    build:
      context: ./
      dockerfile: ./Dockerfile.devel
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_NAME=es_devel
      - REDIS_SERVER=redis
      - RAILS_LOG_TO_STDOUT=true
      - GOOGLE_MAPS_KEY=GOOGLE_MAPS_KEY
      - IPINFO_KEY=IPINFO_KEY
    labels:
      com.centurylinklabs.watchtower.enable: false
    volumes:
      - ./:/eventaservo
    ports:
      - 30000:3000
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2.6
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3

  db:
    image: postgres:13.5
    environment:
      - POSTGRES_PASSWORD=eventaservo
      - POSTGRES_USER=eventaservo
      - POSTGRES_DB=es_devel
    volumes:
      - es_devel_db_data:/var/lib/postgresql/data
      - /backup:/backup

volumes:
  es_devel_db_data:
