# Docker-compose file for DEVELOPMENT containers
version: '3.8'

services:
  redis:
    image: redis:6.2.6
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 6379:6379

  db:
    image: postgres:13.5
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eventaservo_devel
    ports:
      - 5432:5432
