openapi: 3.1.0
info:
  title: EventaServo API
  version: '2.0'
  contact:
    name: Fernando
    url: 'https://github.com/eventaservo'
    email: fernando@eventaservo.org
  termsOfService: 'https://eventaservo.org/LICENSE'
  license:
    name: AGPL-3
    identifier: AGPL-3
  summary: API to list and manage data in EventaServo
servers:
  - url: 'https://localhost:3000/api/v1'
    description: Development
  - url: 'https://eventaservo.org/api/v1'
    description: Production
paths:
  /events.json:
    get:
      summary: Listigas eventojn
      tags:
        - Eventoj
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uuid:
                      type: string
                    kodo:
                      type: string
                    titolo:
                      type: string
                    priskribo:
                      type: string
                    enhavo:
                      type: string
                    komenca_dato:
                      type: string
                    fina_dato:
                      type: string
                    retpagho:
                      type: string
                    retposhtadreso:
                      type: string
                      example: kontakto@eventaservo.org
                    organizoj:
                      type: array
                      items:
                        type: string
                    specoj:
                      type: array
                      items:
                        type: string
                    nuligita:
                      type: boolean
                    nuligkialo:
                      type: string
                    reta:
                      type: string
                    loko:
                      type: object
                      properties:
                        adreso:
                          type: string
                        urbo:
                          type: string
                        lando:
                          type: string
                        landokodo:
                          type: string
                        latitudo:
                          type: number
                        longitudo:
                          type: number
                    administranto:
                      type: string
      operationId: get-events.json
      parameters:
        - schema:
            type: string
            example: '2022-01-01'
            format: date
          in: query
          name: komenca_dato
          required: true
        - schema:
            type: string
            example: '2022-01-31'
            format: date
          in: query
          name: fina_dato
          required: true
        - schema:
            type: string
            format: uuid
            example: e567bdc3-0ea2-46cc-8a83-3b11facbe16c
          in: query
          name: uuid
          allowEmptyValue: true
        - schema:
            type: string
            example: BR
          in: query
          name: landa_kodo
        - schema:
            type: string
            example: UEA
          in: query
          name: o
          description: Organiza mallonga nomo
    parameters: []
components:
  schemas:
    Event:
      description: Detalaj informoj pri la evento
      type: object
      title: Evento
      x-internal: false
      examples: []
      properties:
        uuid:
          type: string
          minLength: 1
        kodo:
          type: string
          minLength: 1
        titolo:
          type: string
          minLength: 1
        priskribo:
          type: string
          minLength: 1
        enhavo:
          type: string
          example: Pli detalaj informoj pri la evento
        komenca_dato:
          type: string
          minLength: 1
        fina_dato:
          type: string
          minLength: 1
        retpaĝo:
          type: string
          minLength: 1
        organizoj:
          type: array
          items:
            type: string
            example: Universala Esperanto-Asocio
        specoj:
          type: array
          items:
            type: string
            example: Internacia
        retpoŝtadreso:
          type: string
          format: email
          example: uea@uea.com
        nuligita:
          type: boolean
        nuligkialo:
          type: string
        reta:
          type: boolean
          description: Reta evento?
        loko:
          type: object
          required:
            - urbo
            - lando
            - landokodo
            - kontinento
            - latitudo
            - longitudo
          properties:
            adreso:
              type: string
            urbo:
              type: string
              minLength: 1
            lando:
              type: string
              minLength: 1
            landokodo:
              type: string
              minLength: 1
            kontinento:
              type: string
              minLength: 1
            latitudo:
              type: number
            longitudo:
              type: number
        administranto:
          type: string
          minLength: 1
      required:
        - uuid
        - kodo
        - titolo
        - priskribo
        - komenca_dato
        - fina_dato
        - retpaĝo
        - organizoj
        - specoj
        - nuligita
        - reta
        - loko
        - administranto
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
