name: Main deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - ".gitpod*"

jobs:
  minitest:
    uses: eventaservo/eventaservo/.github/workflows/template_test.yml
    secrets:
      rails_master_key: ${{ secrets.RAILS_MASTER_KEY }}

  docker:
    needs: minitest
    uses: eventaservo/eventaservo/.github/workflows/docker.yml
    with:
      environment: production
      tag: latest
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

  sentry:
    needs: docker
    uses: eventaservo/eventaservo/.github/workflows/sentry.yml
    with:
      environment: 'production'
    secrets:
      sentry_auth_token: ${{ secrets.SENTRY_AUTH_TOKEN }}
